@extends('layouts.admin', ['title' => 'Purchase Requests | '.company()->display_name])
@section('content')
<section class="bg-pine-50"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="mb-6"><p class="text-sm font-semibold text-pine-500">Purchase Request Automation</p><h1 class="mt-2 text-3xl font-semibold text-ink">ใบขอซื้อวัสดุ</h1><p class="mt-2 text-sm text-pine-700">รายการ PR ที่ระบบสร้างจากวัสดุไม่เพียงพอและรายการที่รออนุมัติ</p></div>
    <div class="grid gap-4 lg:hidden">@foreach($purchaseRequests as $pr)<a href="{{ route('admin.purchase-requests.show', $pr) }}" class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-pine-200"><div class="flex justify-between gap-3"><p class="font-semibold text-ink">{{ $pr->pr_no }}</p><span class="rounded-full bg-pine-100 px-3 py-1 text-xs font-semibold text-pine-700">{{ $pr->status_label }}</span></div><p class="mt-2 text-sm text-pine-700">{{ $pr->material->name }}</p><p class="mt-3 text-xl font-semibold text-ink">{{ number_format((float)$pr->requested_qty, 3) }} {{ $pr->material->unit }}</p></a>@endforeach</div>
    <div class="hidden overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-pine-200 lg:block"><table class="min-w-full divide-y divide-pine-200 text-sm"><thead class="bg-pine-100 text-pine-700"><tr><th class="px-4 py-3 text-left">PR No</th><th class="px-4 py-3 text-left">Material</th><th class="px-4 py-3 text-right">Requested Qty</th><th class="px-4 py-3 text-left">Reason</th><th class="px-4 py-3 text-left">Status</th><th></th></tr></thead><tbody class="divide-y divide-pine-100">@forelse($purchaseRequests as $pr)<tr><td class="px-4 py-3 font-semibold text-ink">{{ $pr->pr_no }}</td><td class="px-4 py-3 text-pine-700">{{ $pr->material->name }}</td><td class="px-4 py-3 text-right">{{ number_format((float)$pr->requested_qty, 3) }} {{ $pr->material->unit }}</td><td class="px-4 py-3 text-pine-700">{{ $pr->reason }}</td><td class="px-4 py-3"><span class="rounded-full bg-pine-100 px-3 py-1 text-xs font-semibold text-pine-700">{{ $pr->status_label }}</span></td><td class="px-4 py-3 text-right"><a href="{{ route('admin.purchase-requests.show', $pr) }}" class="rounded-lg bg-pine-50 px-3 py-2 font-semibold text-pine-700">View</a></td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center text-pine-700">ยังไม่มี PR</td></tr>@endforelse</tbody></table></div>
    <div class="mt-6">{{ $purchaseRequests->links() }}</div>
</div></section>
@endsection
