<?php

use App\Http\Controllers\AdminLeadController;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\AdminFacebookSettingController;
use App\Http\Controllers\AdminInventoryController;
use App\Http\Controllers\AdminInstallationScheduleController;
use App\Http\Controllers\AdminCustomerReviewController;
use App\Http\Controllers\AdminLineSettingController;
use App\Http\Controllers\AdminMarketingHomepageController;
use App\Http\Controllers\AdminPortfolioController;
use App\Http\Controllers\AdminProductController;
use App\Http\Controllers\AdminProductionController;
use App\Http\Controllers\AdminPurchaseController;
use App\Http\Controllers\AdminQuotationController;
use App\Http\Controllers\AdminSupplierController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\FacebookWebhookController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\ReviewController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::view('/bedroom-set', 'bedroom-set')->name('bedroom-set');
Route::get('/portfolio', [PortfolioController::class, 'index'])->name('portfolio.index');
Route::get('/reviews', [ReviewController::class, 'index'])->name('reviews.index');
Route::view('/lead', 'lead')->name('lead.create');
Route::post('/lead', [LeadController::class, 'store'])->name('lead.store');
Route::view('/thank-you', 'thank-you')->name('thank-you');
Route::get('/webhooks/facebook', [FacebookWebhookController::class, 'verify'])->name('webhooks.facebook.verify');
Route::post('/webhooks/facebook', [FacebookWebhookController::class, 'receive'])->name('webhooks.facebook.receive');

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.store');
});

Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');

Route::middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    Route::get('/leads', [AdminLeadController::class, 'index'])->name('leads.index');
    Route::get('/leads/export', [AdminLeadController::class, 'export'])->name('leads.export');
    Route::get('/leads/{lead}', [AdminLeadController::class, 'show'])->name('leads.show');
    Route::patch('/leads/{lead}', [AdminLeadController::class, 'update'])->name('leads.update');
    Route::patch('/leads/{lead}/status', [AdminLeadController::class, 'updateStatus'])->name('leads.status');
    Route::post('/leads/{lead}/notes', [AdminLeadController::class, 'storeNote'])->name('leads.notes.store');
    Route::get('/leads/{lead}/quotations/create', [AdminQuotationController::class, 'create'])->name('leads.quotations.create');
    Route::post('/leads/{lead}/quotations', [AdminQuotationController::class, 'store'])->name('leads.quotations.store');
    Route::get('/quotations/{quotation}', [AdminQuotationController::class, 'show'])->name('quotations.show');
    Route::patch('/quotations/{quotation}/status', [AdminQuotationController::class, 'updateStatus'])->name('quotations.status');
    Route::get('/quotations/{quotation}/pdf', [AdminQuotationController::class, 'pdf'])->name('quotations.pdf');
    Route::get('/production', [AdminProductionController::class, 'index'])->name('production.index');
    Route::get('/production/{productionOrder}', [AdminProductionController::class, 'show'])->name('production.show');
    Route::patch('/production/{productionOrder}/status', [AdminProductionController::class, 'updateStatus'])->name('production.status');
    Route::patch('/production/{productionOrder}/craftsmen', [AdminProductionController::class, 'assignCraftsmen'])->name('production.craftsmen');
    Route::get('/installation-schedule', [AdminInstallationScheduleController::class, 'index'])->name('installation.index');
    Route::get('/products', [AdminProductController::class, 'index'])->name('products.index');
    Route::get('/inventory', [AdminInventoryController::class, 'index'])->name('inventory.index');
    Route::post('/inventory/materials/{material}/transactions', [AdminInventoryController::class, 'storeTransaction'])->name('inventory.transactions.store');
    Route::get('/settings/line', [AdminLineSettingController::class, 'edit'])->name('settings.line.edit');
    Route::patch('/settings/line', [AdminLineSettingController::class, 'update'])->name('settings.line.update');
    Route::get('/settings/line/logs', [AdminLineSettingController::class, 'logs'])->name('settings.line.logs');
    Route::get('/settings/facebook', [AdminFacebookSettingController::class, 'edit'])->name('settings.facebook.edit');
    Route::post('/settings/facebook', [AdminFacebookSettingController::class, 'update'])->name('settings.facebook.update');
    Route::get('/marketing/homepage', [AdminMarketingHomepageController::class, 'index'])->name('marketing.homepage');
    Route::post('/marketing/homepage/sections/{section}', [AdminMarketingHomepageController::class, 'updateSection'])->name('marketing.homepage.sections.update');
    Route::post('/marketing/homepage/categories/{category}', [AdminMarketingHomepageController::class, 'updateCategory'])->name('marketing.homepage.categories.update');
    Route::get('/marketing/reviews', [AdminCustomerReviewController::class, 'index'])->name('marketing.reviews.index');
    Route::post('/marketing/reviews', [AdminCustomerReviewController::class, 'store'])->name('marketing.reviews.store');
    Route::patch('/marketing/reviews/{review}', [AdminCustomerReviewController::class, 'update'])->name('marketing.reviews.update');
    Route::delete('/marketing/reviews/{review}', [AdminCustomerReviewController::class, 'destroy'])->name('marketing.reviews.destroy');
    Route::get('/portfolio', [AdminPortfolioController::class, 'index'])->name('portfolio.index');
    Route::post('/portfolio', [AdminPortfolioController::class, 'store'])->name('portfolio.store');
    Route::patch('/portfolio/{portfolioImage}', [AdminPortfolioController::class, 'update'])->name('portfolio.update');
    Route::delete('/portfolio/{portfolioImage}', [AdminPortfolioController::class, 'destroy'])->name('portfolio.destroy');
    Route::resource('suppliers', AdminSupplierController::class)->except('destroy');
    Route::get('/purchase', [AdminPurchaseController::class, 'index'])->name('purchase.index');
    Route::get('/purchase/pr/create', [AdminPurchaseController::class, 'createPr'])->name('purchase.pr.create');
    Route::post('/purchase/pr', [AdminPurchaseController::class, 'storePr'])->name('purchase.pr.store');
    Route::get('/purchase/pr/{purchaseRequisition}', [AdminPurchaseController::class, 'showPr'])->name('purchase.pr.show');
    Route::patch('/purchase/pr/{purchaseRequisition}/status', [AdminPurchaseController::class, 'updatePrStatus'])->name('purchase.pr.status');
    Route::get('/purchase/po/create', [AdminPurchaseController::class, 'createPo'])->name('purchase.po.create');
    Route::post('/purchase/po', [AdminPurchaseController::class, 'storePo'])->name('purchase.po.store');
    Route::get('/purchase/po/{purchaseOrder}', [AdminPurchaseController::class, 'showPo'])->name('purchase.po.show');
    Route::post('/purchase/receive/{purchaseOrderItem}', [AdminPurchaseController::class, 'receive'])->name('purchase.receive');
    Route::post('/purchase/auto-pr/material/{material}', [AdminPurchaseController::class, 'autoPrFromLowStock'])->name('purchase.auto-pr.material');
    Route::post('/purchase/auto-pr/production/{productionOrder}', [AdminPurchaseController::class, 'autoPrFromProduction'])->name('purchase.auto-pr.production');
    Route::get('/purchase/reports/{type}/{format}', [AdminPurchaseController::class, 'report'])->name('purchase.reports.export');
});
