<?php $__env->startSection('content'); ?>
<section class="bg-pine-50"><div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-pine-500">Material Master</p><h1 class="mt-2 text-3xl font-semibold text-ink">วัสดุ</h1></div><a href="<?php echo e(route('admin.materials.create')); ?>" class="w-fit rounded-xl bg-pine-700 px-5 py-3 text-sm font-semibold text-white">เพิ่มวัสดุ</a></div>
    <?php if(session('success')): ?><div class="mb-6 rounded-xl bg-green-50 p-4 text-sm text-green-800 ring-1 ring-green-200"><?php echo e(session('success')); ?></div><?php endif; ?>
    <div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-pine-200">
        <table class="min-w-full divide-y divide-pine-200 text-sm"><thead class="bg-pine-100 text-pine-700"><tr><th class="px-4 py-3 text-left">SKU</th><th class="px-4 py-3 text-left">Name</th><th class="px-4 py-3 text-left">Unit</th><th class="px-4 py-3 text-right">Current Stock</th><th class="px-4 py-3 text-right">Minimum Stock</th><th class="px-4 py-3 text-right">Cost Price</th><th class="px-4 py-3 text-left">Supplier</th><th class="px-4 py-3 text-left">Stock Status</th><th></th></tr></thead>
        <tbody class="divide-y divide-pine-100"><?php $__empty_1 = true; $__currentLoopData = $materials; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $material): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="px-4 py-3 font-semibold text-pine-700"><?php echo e($material->sku ?: '-'); ?></td><td class="px-4 py-3 font-semibold text-ink"><?php echo e($material->name); ?></td><td class="px-4 py-3 text-pine-700"><?php echo e($material->unit); ?></td><td class="px-4 py-3 text-right"><?php echo e(number_format((float)$material->current_stock, 3)); ?></td><td class="px-4 py-3 text-right"><?php echo e(number_format($material->minimum_stock_value, 3)); ?></td><td class="px-4 py-3 text-right">฿<?php echo e(number_format($material->cost_price_value, 2)); ?></td><td class="px-4 py-3 text-pine-700"><?php echo e($material->supplier_name ?: '-'); ?></td><td class="px-4 py-3"><span class="rounded-full px-3 py-1 text-xs font-semibold <?php echo e($material->stock_status === 'ปกติ' ? 'bg-green-50 text-green-700' : ($material->stock_status === 'ใกล้หมด' ? 'bg-amber-50 text-amber-700' : 'bg-rose-50 text-rose-700')); ?>"><?php echo e($material->stock_status); ?></span></td><td class="px-4 py-3 text-right"><a href="<?php echo e(route('admin.materials.edit', $material)); ?>" class="rounded-lg bg-pine-50 px-3 py-2 font-semibold text-pine-700">Edit</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="9" class="px-4 py-10 text-center text-pine-700">ยังไม่มีวัสดุ</td></tr><?php endif; ?></tbody></table>
    </div>
</div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', ['title' => 'วัสดุ | '.company()->display_name], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\BEER\Documents\Codex\2026-06-17\create-a-laravel-12-project-named\wooden-dad-sales-engine\resources\views\admin\materials\index.blade.php ENDPATH**/ ?>