<form method="post" action="{{ $action }}" class="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-pine-200">@csrf @if($method !== 'POST') @method($method) @endif
<div class="grid gap-5 md:grid-cols-2">
<label><span class="text-sm font-semibold text-ink">SKU</span><input name="sku" value="{{ old('sku', $material->sku ?? '') }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label><span class="text-sm font-semibold text-ink">Name</span><input name="name" required value="{{ old('name', $material->name ?? '') }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label><span class="text-sm font-semibold text-ink">Unit</span><input name="unit" required value="{{ old('unit', $material->unit ?? '') }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label><span class="text-sm font-semibold text-ink">Current Stock</span><input name="current_stock" type="number" step="0.001" min="0" value="{{ old('current_stock', $material->current_stock ?? 0) }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label><span class="text-sm font-semibold text-ink">Minimum Stock</span><input name="minimum_stock" type="number" step="0.001" min="0" value="{{ old('minimum_stock', $material->minimum_stock ?? $material->low_stock_level ?? 0) }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label><span class="text-sm font-semibold text-ink">Cost Price</span><input name="cost_price" type="number" step="0.01" min="0" value="{{ old('cost_price', $material->cost_price ?? $material->unit_cost ?? 0) }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
<label class="md:col-span-2"><span class="text-sm font-semibold text-ink">Supplier</span><input name="supplier_name" value="{{ old('supplier_name', $material->supplier_name ?? '') }}" class="mt-2 w-full rounded-xl border-0 bg-pine-50 px-3 py-3 ring-1 ring-pine-200"></label>
</div><button class="mt-6 rounded-xl bg-pine-700 px-5 py-3 text-sm font-semibold text-white">{{ $submitLabel }}</button></form>
